#!/bin/sh

set -e

echo "Setting up your environment..."

if command -v bundle >/dev/null; then
    echo "  + Bundler found."
else
    echo "  x You need to install Bundler:"
    echo "    gem install bundler"
    exit 1
fi

echo "  + Bootstrapping your Rubies."
bundle install --binstubs

echo "Done!"
