#!/bin/sh

set -e

export PATH="$PWD/bin:$PATH"

COOKBOOK_NAME="ps2dev"
COOKBOOKS_PATH="cookbooks"

echo "  + Running RSpec tests..."
mkdir -p "$COOKBOOKS_PATH"
ln -snf ../ "$COOKBOOKS_PATH/$COOKBOOK_NAME"
exec rspec $RSPEC_OPTS "$COOKBOOKS_PATH/$COOKBOOK_NAME"
