#!/bin/sh

set -e

script/bootstrap

COOKBOOK_NAME=ps2dev
RSPEC_COOKBOOKS=cookbooks
export RSPEC_COOKBOOKS

echo "  + Running RSpec tests."
exec bundle exec rspec --color --format documentation \
    --require ./script/rspec-berkshelf.rb "$RSPEC_COOKBOOKS/$COOKBOOK_NAME"
