#!/bin/sh
# Install Gecode which is required by berkshelf gem.

set -e

PACKAGE=libgecode-dev

test -e /etc/debian_version || exit 0
dpkg -s "$PACKAGE" 2>/dev/null | grep -q "Status: install ok installed" && exit 0

echo "  + Installing Gecode."
echo "deb http://apt.opscode.com $(lsb_release -cs)-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list
wget http://apt.opscode.com/packages@opscode.com.gpg.key -O- -q | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y "$PACKAGE"
